mywiki/mywiki/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('vocab.urls')),
    url(r'^admin/', admin.site.urls),
]

mywiki/vocab/urls.py
from django.conf.urls import url

from . import views
app_name = 'wiki'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search$', views.search, name='search'),
    url(r'^searched$', views.searched, name='searched'),
    url(r'^deposit$', views.deposit, name='deposit'),
    url(r'^get_word$', views.get_word, name='get_word'),
    url(r'^upload$', views.upload, name='upload'),
    url(r'^uploaded$', views.uploaded, name='uploaded'),
]

mywiki/vocab/models.py
from django.db import models

# Create your models here.

class Word(models.Model):
    word_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.word_text

class Info(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    type_text = models.CharField(max_length=200)
    meaning_text = models.CharField(max_length=200)
    sentence_text = models.CharField(max_length=200)
    def __str__(self):
        return self.type_text

class SearchFrequency(models.Model):
    frequency = models.CharField(max_length=200)
    def __str__(self):
        return self.frequency

class SearchPopular(models.Model):
    search_word = models.CharField(max_length=200)
    search = models.IntegerField(default=1)
    def __str__(self):
        return self.search_word

mywiki/vocab/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.core.files.storage import default_storage
from .models import Word,Info,SearchFrequency,SearchPopular
from django.utils import timezone
import csv,os
import xml.etree.ElementTree as etree
from django.db.models import Max
# Create your views here.


def index(request):
    return render(request,'index.html',None)


def search(request):
    last_five_search = []
    tmp=[]
    popular = SearchPopular.objects.all().aggregate(Max('search'))
    print(popular)
    for item in SearchPopular.objects.filter(search=popular['search__max']):
        most_popular = item
        break
    for item in SearchFrequency.objects.filter(frequency__icontains=''):
        tmp.append(item.frequency)
    for i in range(len(tmp)-1,-1,-1):
        last_five_search.append(tmp[i])
    context = {'last_five' : last_five_search,'most_popular' : most_popular}
    return render(request,'search.html',context)

	
def searched(request): 
    word = request.GET['word']
    if(word != ''):
        if(SearchPopular.objects.filter(search_word=word)):
            search_add = SearchPopular.objects.filter(search_word=word)
            for item in search_add:
                item.search +=1
                item.save()
        else:
            newSearch = SearchPopular(search_word=word)
            newSearch.save()
        if(SearchFrequency.objects.filter(frequency=word)):
            SearchFrequency.objects.filter(frequency=word).delete()
        newStats = SearchFrequency(frequency=word)
        newStats.save()
        count = 0
        for item in SearchFrequency.objects.filter(frequency__icontains=''):
            count+=1
        if count > 5 :
            for item in SearchFrequency.objects.filter(frequency__icontains=''):
                item.delete()
                count-=1
                if count == 5:
                    break
        for item in SearchFrequency.objects.filter(frequency__icontains=''):
            print(item)
        print('Popular:')
        for item in SearchPopular.objects.filter(search_word__icontains=''):
            print(item.search)
    
    if('method' in str(request)):
        if( request.GET['by'] == 'A-Z'):
            exist_word = Word.objects.filter(word_text=word).order_by('word_text')
        elif( request.GET['by'] == 'Z-A'):
            exist_word = Word.objects.filter(word_text=word).order_by('word_text').reverse()
        else:
            exist_word = Word.objects.filter(word_text=word)
    else:
        if( request.GET['by'] == 'A-Z'):
            exist_word = Word.objects.filter(word_text__icontains=word).order_by('word_text')
        elif( request.GET['by'] == 'Z-A'):
            exist_word = Word.objects.filter(word_text__icontains=word).order_by('word_text').reverse()
        else:
            exist_word = Word.objects.filter(word_text__icontains=word)
    context = { 'word' : exist_word }
    return render(request,'searched.html',context)



def deposit(request):
    context = None
    if(request.GET):
        if(request.GET['status'] == '0'):
            status = 'Word Added'
        elif(request.GET['status'] == '1'):
            status = 'Word Meaning Already exist'
        else:
            status = 'Fill the Form'
        context = { 'status': status}
    return render(request,'deposit.html',context)


def get_word(request):
    word = request.POST['word'].lower()
    meaning = request.POST['meaning'].lower()
    types = request.POST['type']
    sentence = request.POST['sentence']
    exist_word = Word.objects.filter(word_text=word)
    meaning_exist = []
    for exist_meaning in exist_word:
        meaning_exist = exist_meaning.info_set.all().filter(meaning_text=meaning)
        if(meaning_exist != []):
            break
    if(meaning_exist == [] and word != '' and meaning != '' and sentence != ''):
        new_word = Word(word_text=word,pub_date=timezone.now())
        new_word.save()
        new_word.info_set.create(type_text=types,meaning_text=meaning,sentence_text=sentence)
        status = '/deposit?status=0'
    elif(word == '' or meaning == '' or sentence == ''):
        status = '/deposit?status=2'
    else:
        status = '/deposit?status=1'
    return redirect(status)


def upload(request):
    context = None
    if(request.GET):
        print('jesus')
        status = None
        if request.GET['status'] == '0':
             status = 'Upload Complete'
        elif request.GET['status'] == '1':
             status = 'CSV not Supported'
        elif request.GET['status'] == '2':
             status = 'File Type Invalid'
        elif request.GET['status'] == '3':
             status = 'No File Upload'
        context = { 'status': status}
    return render(request,'upload.html',context)

def uploaded(request):
    if request.FILES:
        if '.csv' in str(request.FILES['input_file']):
            path = 'vocab/static/'
            csv_file = request.FILES['input_file']
            file_path = default_storage.save(path, csv_file)
            os.rename(file_path, path+"upload_file.csv")
            with open(path+'upload_file.csv', encoding='utf-8') as csvfile:
                dataReader = csv.DictReader(csvfile)
                isSupport = False
                allKey = []
                for row in dataReader:
                    for key in row:
                        allKey.append(key)
                    print(allKey)
                    if('Word' in allKey and 'Type' in allKey and 'Meaning' in allKey and 'Sentence' in allKey):
                        isSupport = True
                    break
                print(isSupport)
                if isSupport:
                    Type = ['Noun','Verb','Adjective','Adverb','Pronoun','Prepositon','Conjunction','Determiner','Exclamation']
                    for row in dataReader:
                        if(row['Type'] in Type):
                            exist_word = Word.objects.filter(word_text=row['Word'].lower())
                            meaning_exist = []
                            for exist_meaning in exist_word:
                                meaning_exist = exist_meaning.info_set.all().filter(meaning_text=row['Meaning'].lower())
                                if(meaning_exist != []):
                                    break
                            if(meaning_exist == []):
                                if(row['Word'] != '' and row['Meaning'] != '' and row['Sentence'] != ''):
                                    new_word = Word(word_text=row['Word'].lower(),pub_date=timezone.now())
                                    new_word.save()
                                    new_word.info_set.create(type_text=row['Type'],meaning_text=row['Meaning'].lower(),sentence_text=row['Sentence'])
                    status = '/upload?status=0' #upload complete     
                else:
                    status = '/upload?status=1' #csv not support
        elif '.xml' in str(request.FILES['input_file']):
            tree = etree.parse('vocab/static/data.xml').getroot()
            if tree.tag == 'vocabstorage':
                pass
        else:
            status = '/upload?status=2' #not csv file
    else:
        status = '/upload?status=3' #no file choosen
    return redirect(status)

mywiki/vocab/templates/deposit.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'search.css' %}" />
<html>
<title>Deposit Word</title>
<header>
<h1>
<form action="{% url 'wiki:index' %}">
Deposit Word
<input class='button-index' type='submit' value='Main'></form><h1>
</header>
<br>
<div class='select-style''>
<form action="{% url 'wiki:get_word' %}" method='post'>
{% csrf_token %}
<p>Word : <p><input type='text' name='word'>
<p>Type : <p><select id="select" name='type'>
<option>Noun</option>
<option>Verb</option>
<option>Adjective</option>
<option>Adverb</option>
<option>Pronoun</option>
<option>Prepositon</option>
<option>Conjunction</option>
<option>Determiner</option>
<option>Exclamation</option>
</select>
</center>
<p>Meaning : <p><input type='text' name='meaning'>
<p>Sentence : <p><input  type='text' name='sentence'>
<br><br><br><br>
<input class='button' type='submit' value='Deposit'>
</div>
</form>
<br><br>
{% if status %}
<font color="red">{{ status }}</font> 

{% endif %}
</html>

mywiki/vocab/templates/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}" />

<html>
<header>
<title>Word Storage</title>
<div id='header'>
<h1><div id='header_text'>Service</div></h1>
</div>
</header>
<br>
<center>
<a class="button" href="{% url 'wiki:search' %}">Search</a>
<br><br>
<a class="button" href="{% url 'wiki:deposit' %}">Deposit Word</a>
<br><br>
<a class="button" href="{% url 'wiki:upload' %}">Upload Word by CSV</a>
</center>
<br>
</html>

mywiki/vocab/templates/search.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'search.css' %}" />

<html>
<title>Search Word</title>
<header>
<h1>
<form action="{% url 'wiki:index' %}">
Search
<input class='button-index' type='submit' value='Main'></form><h1>
</header>
<br>
<form action="{% url 'wiki:searched' %}" method='get'>
<center><input type='text' name='word' id='text'></center>
<br>
<center>
<div class="select-style">
<select name="by">
<option value ="Date">Date</option>
<option value ="A-Z">A-Z</option>
<option value ="Z-A">Z-A</option>
</select>
<input type="checkbox" name='method' value="Match Word">Match Word
<br><br>
<input class='button' type='submit' value='Search'>
</div>
</center>
</form>
<h1>Last Five Search</h1>
{% if last_five %}
{% for item in last_five %}
    <button class=button_lw onClick="document.getElementById('text').value = '{{ item }}'">{{ item }}</button>
{% endfor %}
{% endif %}
<h1>Popular Word</h1>
{% if most_popular %}
    <button class=button_lw onClick="document.getElementById('text').value = '{{ most_popular }}'">{{ most_popular }}</button>
{% endif %}
</html>

mywiki/vocab/templates/searched.html
{% load staticfiles %}
<title>Result</title>
<link rel="stylesheet" type="text/css" href="{% static 'search.css' %}" />
<html>
<header>
<h1>
<form action="{% url 'wiki:index' %}">
Search Result
<input class='button-index' type='submit' value='Main'></form><h1>
</header>
<br><br>
{% if word %}
  <table style="width:100%">
  <tr>
    <th>Word</th>
    <th>Type</th>
    <th>Meaning</th>
    <th>Example</th>
  </tr>
{% for words in word%}
  <tr>
    <td>{{ words }}</td>
    {% for info in words.info_set.all %}
        <td>{{ info.type_text }}</td>
        <td>{{ info.meaning_text }}</td>
        <td>{{ info.sentence_text }}</td>
    {% endfor %}
  </tr>
{% endfor %}
  </table> 
{% else %}
  No Word Found.
{% endif %}
</html>

mywiki/vocab/templates/upload.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'search.css' %}" />

<html>
<title>Upload Word</title>
<header>
<h1>
<form action="{% url 'wiki:index' %}">
Upload
<input class='button-index' type='submit' value='Main'></form><h1>
</header>
<br>
<center>
<form action="{% url 'wiki:uploaded' %}" method='post' enctype="multipart/form-data">
{% csrf_token %}            
<input type="file" name="input_file" id="input_file">
<br><br>
<input class='button' type="submit" value="Upload CSV File" name="submit">
</form>
<br><br>
{% if status %}
<font color="red">{{ status }}</font> 
{% endif %}
</center>
</html>